
package dashboard;

import java.awt.Color;
import java.awt.Image;
import java.awt.Insets;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

public class homepage extends javax.swing.JFrame {
static SimpleDateFormat timeformat;
static Calendar cal;
static String times;
int height=0, width=0;
    public homepage() {
        initComponents();
        
       
        time();
        icons();
         screenSize();
    }
    
    public void screenSize(){
       Toolkit tk = Toolkit.getDefaultToolkit();
         width = (int)tk.getScreenSize().getWidth();
         height = (int)tk.getScreenSize().getHeight();
        Insets task = Toolkit.getDefaultToolkit().getScreenInsets(getGraphicsConfiguration());
        int h  = task.bottom;
        setSize(width,height-h);
}
    
public void icons(){
  
    left.setIcon(setSize(new ImageIcon(getClass().getResource("/images/left.png")),61,58));
      right.setIcon(setSize(new ImageIcon(getClass().getResource("/images/right.png")),61,58));
         leftabout.setIcon(setSize(new ImageIcon(getClass().getResource("/images/left.png")),61,58));
         rightabout.setIcon(setSize(new ImageIcon(getClass().getResource("/images/right.png")),61,58));
    
}


public static ImageIcon setSize(ImageIcon icon, int width, int height){
     Image i = icon.getImage();
    Image p = i.getScaledInstance(width, height, Image.SCALE_DEFAULT);
    ImageIcon icons = new ImageIcon(p);
    
    return icons;
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        dashboard = new javax.swing.JToggleButton();
        brgyinformation = new javax.swing.JToggleButton();
        brgyofficials = new javax.swing.JToggleButton();
        residentslist = new javax.swing.JToggleButton();
        blotter = new javax.swing.JToggleButton();
        certification = new javax.swing.JToggleButton();
        history = new javax.swing.JToggleButton();
        settings = new javax.swing.JToggleButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        Dashboard = new javax.swing.JPanel();
        unsettledcount = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        settledcount = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        blottercount = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        householdcount = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        seniorcount = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        nonvoterscount = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        voterscount = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        purokcount = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        pwdcount = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        femalecount = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        malecount = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        residentscount = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        BrgyInformation = new javax.swing.JPanel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        aboutpanel = new javax.swing.JPanel();
        titleabout = new javax.swing.JLabel();
        bgimage1 = new javax.swing.JLabel();
        about = new javax.swing.JTextArea();
        rightabout = new javax.swing.JLabel();
        leftabout = new javax.swing.JLabel();
        missionvisionpanel = new javax.swing.JPanel();
        bgimage = new javax.swing.JLabel();
        vision = new javax.swing.JTextArea();
        mission = new javax.swing.JTextArea();
        titlevision = new javax.swing.JLabel();
        titlemission = new javax.swing.JLabel();
        right = new javax.swing.JLabel();
        left = new javax.swing.JLabel();
        BrgyOfficials = new javax.swing.JPanel();
        officialsview = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        dd = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 87, 138));
        jPanel2.setPreferredSize(new java.awt.Dimension(280, 809));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setBackground(new java.awt.Color(255, 255, 255));
        logo.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LOGO JOLLY CODE PNG.png"))); // NOI18N
        logo.setText("LOGO");
        logo.setBorder(null);
        logo.setPreferredSize(new java.awt.Dimension(152, 152));
        jPanel2.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 160, 170));

        dashboard.setBackground(new java.awt.Color(0, 87, 138));
        buttonGroup1.add(dashboard);
        dashboard.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        dashboard.setForeground(new java.awt.Color(255, 255, 255));
        dashboard.setText("     Dashboard");
        dashboard.setBorder(null);
        dashboard.setBorderPainted(false);
        dashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dashboard.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardActionPerformed(evt);
            }
        });
        jPanel2.add(dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 280, 40));

        brgyinformation.setBackground(new java.awt.Color(0, 87, 138));
        buttonGroup1.add(brgyinformation);
        brgyinformation.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        brgyinformation.setForeground(new java.awt.Color(255, 255, 255));
        brgyinformation.setText("     Brgy. Information");
        brgyinformation.setBorder(null);
        brgyinformation.setBorderPainted(false);
        brgyinformation.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        brgyinformation.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        brgyinformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brgyinformationActionPerformed(evt);
            }
        });
        jPanel2.add(brgyinformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 280, 40));

        brgyofficials.setBackground(new java.awt.Color(0, 87, 138));
        buttonGroup1.add(brgyofficials);
        brgyofficials.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        brgyofficials.setForeground(new java.awt.Color(255, 255, 255));
        brgyofficials.setText("     Brgy. Officials");
        brgyofficials.setBorder(null);
        brgyofficials.setBorderPainted(false);
        brgyofficials.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        brgyofficials.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        brgyofficials.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brgyofficialsActionPerformed(evt);
            }
        });
        jPanel2.add(brgyofficials, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 280, 40));

        residentslist.setBackground(new java.awt.Color(0, 87, 138));
        buttonGroup1.add(residentslist);
        residentslist.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        residentslist.setForeground(new java.awt.Color(255, 255, 255));
        residentslist.setText("     Residents List");
        residentslist.setBorder(null);
        residentslist.setBorderPainted(false);
        residentslist.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        residentslist.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        residentslist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                residentslistActionPerformed(evt);
            }
        });
        jPanel2.add(residentslist, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 280, 40));

        blotter.setBackground(new java.awt.Color(0, 87, 138));
        buttonGroup1.add(blotter);
        blotter.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        blotter.setForeground(new java.awt.Color(255, 255, 255));
        blotter.setText("     Blotter");
        blotter.setBorder(null);
        blotter.setBorderPainted(false);
        blotter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        blotter.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        blotter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blotterActionPerformed(evt);
            }
        });
        jPanel2.add(blotter, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 280, 40));

        certification.setBackground(new java.awt.Color(0, 87, 138));
        buttonGroup1.add(certification);
        certification.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        certification.setForeground(new java.awt.Color(255, 255, 255));
        certification.setText("     Certification");
        certification.setBorder(null);
        certification.setBorderPainted(false);
        certification.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        certification.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        certification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                certificationActionPerformed(evt);
            }
        });
        jPanel2.add(certification, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 280, 40));

        history.setBackground(new java.awt.Color(0, 87, 138));
        buttonGroup1.add(history);
        history.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        history.setForeground(new java.awt.Color(255, 255, 255));
        history.setText("     History");
        history.setBorder(null);
        history.setBorderPainted(false);
        history.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        history.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        history.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historyActionPerformed(evt);
            }
        });
        jPanel2.add(history, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 280, 40));

        settings.setBackground(new java.awt.Color(0, 87, 138));
        buttonGroup1.add(settings);
        settings.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        settings.setForeground(new java.awt.Color(255, 255, 255));
        settings.setText("     Settings");
        settings.setBorder(null);
        settings.setBorderPainted(false);
        settings.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        settings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsActionPerformed(evt);
            }
        });
        jPanel2.add(settings, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 650, 280, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Dashboard.setBackground(new java.awt.Color(255, 255, 255));
        Dashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        unsettledcount.setFont(new java.awt.Font("Novecento Bold", 1, 48)); // NOI18N
        unsettledcount.setForeground(new java.awt.Color(255, 255, 255));
        unsettledcount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        unsettledcount.setText("2");
        Dashboard.add(unsettledcount, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 570, 200, -1));

        jLabel44.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("UNSETTLE CASES");
        Dashboard.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 540, -1, -1));

        settledcount.setFont(new java.awt.Font("Novecento Bold", 1, 48)); // NOI18N
        settledcount.setForeground(new java.awt.Color(255, 255, 255));
        settledcount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        settledcount.setText("6");
        Dashboard.add(settledcount, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 570, 200, -1));

        jLabel42.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("SETTLED CASES");
        Dashboard.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 540, -1, -1));

        blottercount.setFont(new java.awt.Font("Novecento Bold", 1, 48)); // NOI18N
        blottercount.setForeground(new java.awt.Color(255, 255, 255));
        blottercount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        blottercount.setText("8");
        Dashboard.add(blottercount, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 570, 200, -1));

        jLabel40.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("BLOTTER CASES");
        Dashboard.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 540, -1, -1));

        householdcount.setFont(new java.awt.Font("Novecento Bold", 1, 48)); // NOI18N
        householdcount.setForeground(new java.awt.Color(255, 255, 255));
        householdcount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        householdcount.setText("38");
        Dashboard.add(householdcount, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 570, 210, -1));

        jLabel38.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("HOUSEHOLD");
        Dashboard.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 540, -1, -1));

        seniorcount.setFont(new java.awt.Font("Novecento Bold", 1, 48)); // NOI18N
        seniorcount.setForeground(new java.awt.Color(255, 255, 255));
        seniorcount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        seniorcount.setText("12");
        Dashboard.add(seniorcount, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 380, 200, -1));

        jLabel36.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("SENIOR CITIZEN");
        Dashboard.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 350, -1, -1));

        nonvoterscount.setFont(new java.awt.Font("Novecento Bold", 1, 48)); // NOI18N
        nonvoterscount.setForeground(new java.awt.Color(255, 255, 255));
        nonvoterscount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nonvoterscount.setText("96");
        Dashboard.add(nonvoterscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 380, 200, -1));

        jLabel28.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("NON-VOTERS");
        Dashboard.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 350, -1, -1));

        voterscount.setFont(new java.awt.Font("Novecento Bold", 1, 48)); // NOI18N
        voterscount.setForeground(new java.awt.Color(255, 255, 255));
        voterscount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        voterscount.setText("56");
        Dashboard.add(voterscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 380, 200, -1));

        jLabel26.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("VOTERS");
        Dashboard.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, -1, -1));

        purokcount.setFont(new java.awt.Font("Novecento Bold", 1, 48)); // NOI18N
        purokcount.setForeground(new java.awt.Color(255, 255, 255));
        purokcount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        purokcount.setText("5");
        Dashboard.add(purokcount, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 200, -1));

        jLabel24.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("NO. OF PUROK");
        Dashboard.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, -1, -1));

        pwdcount.setFont(new java.awt.Font("Novecento Bold", 1, 48)); // NOI18N
        pwdcount.setForeground(new java.awt.Color(255, 255, 255));
        pwdcount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pwdcount.setText("5");
        Dashboard.add(pwdcount, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 200, 200, -1));

        jLabel22.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("PWD");
        Dashboard.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 170, -1, -1));

        femalecount.setFont(new java.awt.Font("Novecento Bold", 1, 48)); // NOI18N
        femalecount.setForeground(new java.awt.Color(255, 255, 255));
        femalecount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        femalecount.setText("70");
        Dashboard.add(femalecount, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 200, 200, -1));

        jLabel20.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("FEMALE");
        Dashboard.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 170, -1, -1));

        malecount.setFont(new java.awt.Font("Novecento Bold", 1, 48)); // NOI18N
        malecount.setForeground(new java.awt.Color(255, 255, 255));
        malecount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        malecount.setText("82");
        Dashboard.add(malecount, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 210, -1));

        jLabel18.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("MALE");
        Dashboard.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, -1, -1));

        residentscount.setFont(new java.awt.Font("Novecento Bold", 1, 48)); // NOI18N
        residentscount.setForeground(new java.awt.Color(255, 255, 255));
        residentscount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        residentscount.setText("152");
        Dashboard.add(residentscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 200, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("RESIDENTS");
        Dashboard.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/I.png"))); // NOI18N
        Dashboard.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 150, 220, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/2.png"))); // NOI18N
        Dashboard.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 520, 220, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/3.png"))); // NOI18N
        Dashboard.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 330, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/4.png"))); // NOI18N
        Dashboard.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 150, 220, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/3.png"))); // NOI18N
        jLabel2.setText("jLabel1");
        Dashboard.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 520, 220, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/5.png"))); // NOI18N
        Dashboard.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/7.png"))); // NOI18N
        Dashboard.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 520, 220, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/I.png"))); // NOI18N
        Dashboard.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 520, 220, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/9.png"))); // NOI18N
        jLabel3.setText("jLabel1");
        Dashboard.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 330, 220, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/8.png"))); // NOI18N
        Dashboard.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 220, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/11.png"))); // NOI18N
        Dashboard.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/2.png"))); // NOI18N
        Dashboard.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 220, -1));

        jLabel6.setFont(new java.awt.Font("Novecento Bold", 0, 42)); // NOI18N
        jLabel6.setText("DASHBOARD");
        Dashboard.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 280, 50));

        jLabel7.setFont(new java.awt.Font("Novecento Book", 0, 20)); // NOI18N
        jLabel7.setText("OVERVIEW");
        Dashboard.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 100, -1));

        jLabel29.setFont(new java.awt.Font("Novecento Bold", 1, 48)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("152");
        Dashboard.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, -1, -1));

        jLabel30.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("RESIDENTS");
        Dashboard.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        jLabel31.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("RESIDENTS");
        Dashboard.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        jLabel32.setFont(new java.awt.Font("Novecento Bold", 1, 48)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("152");
        Dashboard.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, -1, -1));

        jLabel33.setFont(new java.awt.Font("Novecento Bold", 1, 48)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("152");
        Dashboard.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 410, -1, -1));

        jLabel34.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("RESIDENTS");
        Dashboard.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 380, -1, -1));

        jLayeredPane1.add(Dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1650, 750));

        BrgyInformation.setBackground(new java.awt.Color(255, 255, 255));
        BrgyInformation.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        aboutpanel.setBackground(new java.awt.Color(255, 255, 255));
        aboutpanel.setForeground(new java.awt.Color(255, 255, 255));
        aboutpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleabout.setFont(new java.awt.Font("Novecento Bold", 1, 48)); // NOI18N
        titleabout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleabout.setText("ABOUT");
        titleabout.setBorder(null);
        aboutpanel.add(titleabout, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 30, 1060, -1));

        bgimage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/footer.png"))); // NOI18N
        bgimage1.setText("fdsg");
        bgimage1.setBorder(null);
        aboutpanel.add(bgimage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 1270, 345));

        about.setColumns(20);
        about.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        about.setLineWrap(true);
        about.setRows(5);
        about.setText("      Barangay JollyCode is an urban barangay that lies between Barangay I and Barangay II in the municipality of Labo, province of Camarines Norte. The barangay has a land area of 16.00 square kilometers or 6.18 square miles which constitutes 2.02% of Labo's total area. Its population as determined by the 2020 Census was 1,700. This represented 7.74% of the total population of Labo.");
        about.setBorder(null);
        aboutpanel.add(about, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 1060, 210));

        rightabout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rightabout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rightaboutMouseClicked(evt);
            }
        });
        aboutpanel.add(rightabout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 290, 61, 58));

        leftabout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        leftabout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                leftaboutMouseClicked(evt);
            }
        });
        aboutpanel.add(leftabout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 61, 58));

        jLayeredPane2.add(aboutpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1650, 740));

        missionvisionpanel.setBackground(new java.awt.Color(255, 255, 255));
        missionvisionpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bgimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/footer.png"))); // NOI18N
        bgimage.setBorder(null);
        missionvisionpanel.add(bgimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 1270, 345));

        vision.setEditable(false);
        vision.setBackground(new java.awt.Color(255, 255, 255));
        vision.setColumns(20);
        vision.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        vision.setLineWrap(true);
        vision.setRows(5);
        vision.setText("     To live in a peaceful, progressive and friendly neighborhood consists of a community of healthy and happy people with deep respect to one another and to the environment that has affected change towards the sustainable development in the municipality.");
        vision.setBorder(null);
        vision.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        vision.setMinimumSize(new java.awt.Dimension(383, 393));
        vision.setRequestFocusEnabled(false);
        missionvisionpanel.add(vision, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 120, 450, -1));

        mission.setEditable(false);
        mission.setBackground(new java.awt.Color(255, 255, 255));
        mission.setColumns(20);
        mission.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        mission.setLineWrap(true);
        mission.setRows(5);
        mission.setText("     To promote total well-being of the residents with participation and cooperation in different projects for development. The officials leads in creating realistic and sustainable programs thru collaboration with different organizations, higher government agencies and other neighboring barangays while cultivating history and culture, and ensuring the cleanliness of the environment.");
        mission.setBorder(null);
        mission.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        mission.setMinimumSize(new java.awt.Dimension(383, 393));
        mission.setRequestFocusEnabled(false);
        missionvisionpanel.add(mission, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 450, -1));

        titlevision.setFont(new java.awt.Font("Novecento Bold", 1, 48)); // NOI18N
        titlevision.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlevision.setText("VISION");
        missionvisionpanel.add(titlevision, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 30, 440, -1));

        titlemission.setFont(new java.awt.Font("Novecento Bold", 1, 48)); // NOI18N
        titlemission.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlemission.setText("MISSION");
        missionvisionpanel.add(titlemission, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 440, -1));

        right.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/right1.png"))); // NOI18N
        right.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        right.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rightMouseClicked(evt);
            }
        });
        missionvisionpanel.add(right, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 290, 61, 58));

        left.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/left1.png"))); // NOI18N
        left.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        left.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                leftMouseClicked(evt);
            }
        });
        missionvisionpanel.add(left, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 61, 58));

        jLayeredPane2.add(missionvisionpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1650, 740));

        BrgyInformation.add(jLayeredPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1650, 740));

        jLayeredPane1.add(BrgyInformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1650, -1));

        BrgyOfficials.setBackground(new java.awt.Color(255, 255, 255));
        BrgyOfficials.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        officialsview.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BrgyOfficials.add(officialsview, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 371, 512));

        jLabel17.setFont(new java.awt.Font("Novecento Bold", 0, 42)); // NOI18N
        jLabel17.setText("BARANGAY OFFICIALS");
        BrgyOfficials.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 470, 50));

        jLayeredPane1.add(BrgyOfficials, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1650, 740));

        jPanel1.add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 1650, 740));

        time.setFont(new java.awt.Font("Novecento Book", 0, 18)); // NOI18N
        jPanel1.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 340, 30));

        dd.setFont(new java.awt.Font("Novecento Book", 0, 18)); // NOI18N
        jPanel1.add(dd, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 340, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1929, 808));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void brgyinformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brgyinformationActionPerformed
        //BrgyInformation.show();
        aboutpanel.setVisible(true);
        Dashboard.setVisible(false);
         BrgyOfficials.setVisible(false);
    }//GEN-LAST:event_brgyinformationActionPerformed

    private void dashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardActionPerformed
        Dashboard.setVisible(true);
        aboutpanel.setVisible(false);
         BrgyOfficials.setVisible(false);
    }//GEN-LAST:event_dashboardActionPerformed

    private void residentslistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_residentslistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_residentslistActionPerformed

    private void brgyofficialsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brgyofficialsActionPerformed
        BrgyOfficials.setVisible(true);
        Dashboard.setVisible(false);
        aboutpanel.setVisible(false);
    }//GEN-LAST:event_brgyofficialsActionPerformed

    private void settingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_settingsActionPerformed

    private void blotterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blotterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_blotterActionPerformed

    private void certificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_certificationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_certificationActionPerformed

    private void historyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_historyActionPerformed

    private void leftMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leftMouseClicked
        aboutpanel.setVisible(true);
        missionvisionpanel.setVisible(false);
    }//GEN-LAST:event_leftMouseClicked

    private void rightaboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rightaboutMouseClicked
        missionvisionpanel.setVisible(true);
        aboutpanel.setVisible(false);
        
    }//GEN-LAST:event_rightaboutMouseClicked

    private void leftaboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leftaboutMouseClicked
        missionvisionpanel.setVisible(true);
        aboutpanel.setVisible(false);
    }//GEN-LAST:event_leftaboutMouseClicked

    private void rightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rightMouseClicked
        aboutpanel.setVisible(true);
        missionvisionpanel.setVisible(false);
    }//GEN-LAST:event_rightMouseClicked

    /**
     * @param args the command line arguments
     */
     static String days;
    public void time(){
          
            
        Thread t = new Thread(){
            @Override
            public void run(){
                while(true){
                    Date d = new Date();
                    SimpleDateFormat datess = new SimpleDateFormat("dd MMMM yyyy");
                    String val = datess.format(d);
                   timeformat = new SimpleDateFormat("hh:mm:ss a");
                    times = timeformat.format(Calendar.getInstance().getTime());
                    
                    
                    switch(d.getDay()){
                        case 0: days="Sun"; break;
                        case 1: days="Mon"; break;
                        case 2: days="Tue"; break;
                        case 3: days="Wed"; break;
                        case 4: days="Thur"; break;
                        case 5: days="Fri"; break;
                        case 6: days="Sat"; break;
                    }
                    time.setText(times+" " + days);
                    dd.setText(val);
                    try {
                        Thread.sleep(1000);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(homepage.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        };
         
             t.start();  
          
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homepage().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BrgyInformation;
    private javax.swing.JPanel BrgyOfficials;
    private javax.swing.JPanel Dashboard;
    private javax.swing.JTextArea about;
    private javax.swing.JPanel aboutpanel;
    private javax.swing.JLabel bgimage;
    private javax.swing.JLabel bgimage1;
    private javax.swing.JToggleButton blotter;
    private javax.swing.JLabel blottercount;
    private javax.swing.JToggleButton brgyinformation;
    private javax.swing.JToggleButton brgyofficials;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JToggleButton certification;
    private javax.swing.JToggleButton dashboard;
    public static javax.swing.JLabel dd;
    private javax.swing.JLabel femalecount;
    private javax.swing.JToggleButton history;
    private javax.swing.JLabel householdcount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private static javax.swing.JLabel left;
    private static javax.swing.JLabel leftabout;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel malecount;
    private javax.swing.JTextArea mission;
    private javax.swing.JPanel missionvisionpanel;
    private javax.swing.JLabel nonvoterscount;
    private javax.swing.JLabel officialsview;
    private javax.swing.JLabel purokcount;
    private javax.swing.JLabel pwdcount;
    private javax.swing.JLabel residentscount;
    private javax.swing.JToggleButton residentslist;
    private static javax.swing.JLabel right;
    private static javax.swing.JLabel rightabout;
    private javax.swing.JLabel seniorcount;
    private javax.swing.JToggleButton settings;
    private javax.swing.JLabel settledcount;
    public static javax.swing.JLabel time;
    private javax.swing.JLabel titleabout;
    private javax.swing.JLabel titlemission;
    private javax.swing.JLabel titlevision;
    private javax.swing.JLabel unsettledcount;
    private javax.swing.JTextArea vision;
    private javax.swing.JLabel voterscount;
    // End of variables declaration//GEN-END:variables
}
