/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package terms_condition;
import managementsystem.LogIn;
import java.awt.Image;
import java.awt.Insets;
import javax.swing.ImageIcon;

/**
 *
 * @author Jester Salen
 */
public class terms extends javax.swing.JFrame {

    /**
     * Creates new form terms
     */
    public terms() {
       setUndecorated(true);
        initComponents();
        foot();
        content();
      
    }
    
    public void content(){
        String val= "As a user of JollyCode's Barangay Management System, you are bound by the following terms and conditions. You should check the terms and conditions regularly.  • Our mission is to provide a management system for your barangay. This means that you will need to input data in our system. Do not worry because we will treat your data with utmost confidentiality.  • Do not use our system for illegal things. Our team develop this system to help every barangay in record-keeping. Using our system in a bad way is strictly prohibited.  • Be a responsible user. As a user who benefit from this system, you should be careful in the things you will do inside in order to avoid system shutdown.  If you wish to contact the developers, you may send email via ";
        val = val.replaceAll("  ", "\n\n");
        
        cont.setText(val);
    }
public void foot(){
    footer.setIcon(setSize(new ImageIcon(getClass().getResource("/images/footer.png")),footer.getWidth(), footer.getHeight()));
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lastModified = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cont = new javax.swing.JTextArea();
        footer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Novecento Bold", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TERMS & CONDITION ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 40));

        jButton1.setBackground(new java.awt.Color(0, 204, 255));
        jButton1.setFont(new java.awt.Font("Novecento Bold", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("I AGREE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 473, 100, 30));

        lastModified.setFont(new java.awt.Font("Novecento Narrow Book", 0, 14)); // NOI18N
        lastModified.setForeground(new java.awt.Color(0, 0, 0));
        lastModified.setText("Last Modified: October 17, 2022");
        jPanel1.add(lastModified, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 230, -1));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportBorder(null);

        cont.setEditable(false);
        cont.setBackground(new java.awt.Color(255, 255, 255));
        cont.setForeground(new java.awt.Color(0, 0, 0));
        cont.setLineWrap(true);
        cont.setWrapStyleWord(true);
        cont.setBorder(null);
        cont.setMargin(new java.awt.Insets(10, 10, 10, 10));
        jScrollPane1.setViewportView(cont);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 390, 330));

        footer.setBackground(new java.awt.Color(102, 204, 255));
        jPanel1.add(footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 410, 115));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        LogIn l = new LogIn();
      LogIn.check.setSelected(true);
        l.show();
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    
    
    
      public static ImageIcon setSize(ImageIcon icon, int width, int height){
            
            Image img = icon.getImage();
            Image scale = img.getScaledInstance(width, height, Image.SCALE_DEFAULT);
            ImageIcon icons = new ImageIcon(scale);
            
            return icons;
            
           
        }
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(terms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(terms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(terms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(terms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new terms().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea cont;
    private javax.swing.JLabel footer;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lastModified;
    // End of variables declaration//GEN-END:variables
}
